//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Course_Id { get; set; }
        public string Course_Description { get; set; }
        public string Course_Name { get; set; }
        public Nullable<System.DateTime> Course_Date { get; set; }
        public int Trainer_Id { get; set; }
        public Nullable<int> SeatsCount { get; set; }
        public int Duration { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
